export const queryKeys = {
  commandes: ["commandes"] as const,
  commande: (id: string) => ["commandes", id] as const,
  produits: ["produits"] as const,
  produit: (id: string) => ["produits", id] as const,
  employes: ["employes"] as const,
  mouvements: ["mouvements"] as const,
  receptions: ["receptions"] as const,
  pointage: ["pointage"] as const,
  pointageOpen: ["pointage", "open"] as const,
  pointageJournal: (date: string) => ["pointage", "journal", date] as const,
  dashboard: ["dashboard"] as const,
  stock: ["stock"] as const,
  alertes: ["alertes"] as const,
  commandesChine: ["commandes-chine"] as const,
  commandeChine: (id: string) => ["commandes-chine", id] as const,
};